import { BACKPACK_CONFIG, ARENA_CONFIG } from '../config.js'

export const initState = () => ({
  playerName: '修仙者',
  currentRealmId: 1,
  currentLevel: 1,
  currentExp: 0,
  level: 1,
  levelExp: 0,
  levelMaxExp: 120,
  totalKillCount: 0,
  realmKillCount: 0,
  currentHp: 200,
  isPlayerDead: false,
  baseAttribute: {
    power: 0,
    constitution: 0,
    agility: 0,
    comprehension: 0,
    luck: 0,
  },
  freeAttributePoint: 0,
  reincarnationCount: 0,
  gold: 1000,
  items: {
    strengthenStone: 0,
    upgradeStone: 0,
    starStone: 0,
    resetPill: 0,
    arenaCoin: 0,
  },
  bagEquipments: [],
  equippedEquipments: {
    weapon: null,
    helmet: null,
    armor: null,
    belt: null,
    shoes: null,
    necklace: null,
    ring: null,
    bracers: null,
  },
  currentMapId: 1,
  currentMonster: null,
  autoBattle: false,
  autoMeditate: false,
  trialCurrentLayer: 1,
  trialMaxLayer: 1,
  trialMonster: null,
  shopItems: [],
  lastSaveTime: Date.now(),
  age: 16,
  isContinuousAttacking: false,
  continuousAttackTimerId: null,
  maxSetCount: 0,
  monsterKillCount: {},
  eliteKillCount: 0,
  rareKillCount: 0,
  achievementState: {},
  maxStrengthenLevel: 0,
  maxStarLevel: 0,
  totalGoldGet: 0,
  signInData: {
    lastSignDate: '',
    totalSignDays: 0,
    cycleSignDays: 0,
  },
  onlineData: {
    totalOnlineTime: 0,
    todayOnlineTime: 0,
    claimedRewards: [],
    lastOnlineTime: Date.now(),
  },
  pills: {
    expPill: 0,
    superExpPill: 0,
    attackPill: 0,
    defensePill: 0,
    resetPill: 0,
  },
  buffData: {
    attackPill: { endTime: 0 },
    defensePill: { endTime: 0 },
  },
  skills: {
    passive: [],
    active: [],
    equippedPassive: [],
    equippedActive: null,
    cd: {}
  },
  sect: {
    id: 0,
    name: '',
    rank: 0,
    contrib: 0,
    dailyTask: null,
    taskProgress: 0
  },
  cave: {
    spiritArrayLv: 1,
    spiritField: [],
    refineStoveLv: 1,
    pillStoveLv: 1
  },
  root: { grade: 0, quality: 0 },
  meridian: { unlocked: 0, lit: 0 },
  secret: {
    unlockCount: 0,
    available: false
  },
  heartDevilTest: false,
  shield: 0,
  isAscended: false,
  immortalRealmId: 0,
  immortalLevel: 1,
  immortalExp: 0,
  lastOfflineTime: Date.now(),
  offlineReward: null,
  pets: [],
  currentPetId: null,
  petHatchProgress: null,
  skyTowerCurrentLayer: 1,
  skyTowerMaxLayer: 1,
  skyTowerMonster: null,
  skyTowerDebuff: null,
  arenaRank: ARENA_CONFIG.baseRank,
  arenaChallengeTimes: ARENA_CONFIG.challengeTimes,
  arenaLastResetTime: Date.now(),
  arenaSeason: 1,
  arenaSeasonEndTime: Date.now() + ARENA_CONFIG.seasonDays * 86400000,
  battleSpeed: 1,
  backpack: {
    slots: Array(BACKPACK_CONFIG.initCapacity).fill(null),
    capacity: BACKPACK_CONFIG.initCapacity,
    maxUnlockedCapacity: BACKPACK_CONFIG.initCapacity,
  }
})